tech_blog/my_app/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "my_app"

urlpatterns = [
    path('', views.PublishedBlogListView.as_view(), name='index'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('new_post/', views.BlogCreateView.as_view(), name="new_post"),
    # Change these to blog/...
    path('drafts/', views.DraftBlogListView.as_view(), name='drafts'),
    path('detail/<int:pk>', views.BlogDetailView.as_view(), name='detail'),
    path('update/<int:pk>', views.BlogUpdateView.as_view(), name="update"),
    path('delete/<int:pk>', views.BlogDeleteView.as_view(), name="delete"),
    path('blog/<int:pk>/publish', views.blog_publish, name="blog_publish"),
    # path('comment/create', views.create_comment, name='create_comment'),
    path('comment/<int:pk>/approve', views.comment_approve, name='comment_approve'),
    path('comment/<int:pk>/reject', views.comment_reject, name='comment_reject'),


]

tech_blog/tech_blog/urls.py
from django.contrib import admin, auth
from django.urls import path, include
from my_app import views
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('my_app.urls')),
    path('login/', LoginView.as_view(template_name="my_app/login.html"), name="login"),
    path('logout/',LogoutView.as_view(next_page="/"), name="logout"),#, kwargs={'next_page':'/'}),
]

tech_blog/my_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone

# Create your models here.
class Blog(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=125)
    content = models.TextField(max_length=512) #Check the max length
    state = models.BooleanField(default=False)
    publish_date = models.DateTimeField(null=True, blank=True)

    def publish(self):
        self.state = True
        self.publish_date = timezone.now()
        self.save()

    def __str__(self) -> str:
        return self.user.username
    
    # After a blog has been created, where should the website take them
    def get_absolute_url(self):
        return reverse("my_app:detail", kwargs={"pk": self.pk})
    
class Comment(models.Model):
    author = models.CharField(max_length=256) #Change to charfield
    blog = models.ForeignKey(Blog, related_name='comments' , on_delete=models.CASCADE)
    content = models.TextField(max_length=512)
    status = models.BooleanField(default = False)
    create_date = models.DateTimeField(null=True, default=None)

    def approve(self):
        self.status = True
        self.save()

    def __str__(self) -> str:
        return self.author

    

tech_blog/my_app/forms.py
from django import forms
from django import forms
from .models import Blog, Comment

class BlogForm(forms.ModelForm):
    # NB: Meta has to be capitalized
    class Meta:
        model = Blog
        fields = ("title", "content",)

    # From django docs
    # https://docs.djangoproject.com/en/4.0/ref/forms/widgets/
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({'class': 'textinputclass'})
        self.fields['content'].widget.attrs.update({'class': 'editable medium-editor-textarea blog_content'})

    # # From udemy:
    # widgets = {
    #     'title': forms.TextInput(attrs={'class':'textinputclass'}),
    #     'text': forms.Textarea(attrs={'class':'editable medium-editor-textarea postcontent'}),
    # }
    


class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment
        fields = ("author","content",)

    # From django docs
    # https://docs.djangoproject.com/en/4.0/ref/forms/widgets/
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['author'].widget.attrs.update({'class': 'textinputclass'})
        self.fields['content'].widget.attrs.update({'class': 'editable medium-editor-textarea'})

    # # From udemy:
    # widgets = {
    #     'author': forms.TextInput(attrs={'class':'textinputclass'}),
    #     'text': forms.Textarea(attrs={'class':'editable medium-editor-textarea'}),
    # }

tech_blog/my_app/views.py
from django.db import models
from django.db.models import fields
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import (TemplateView, ListView, DeleteView, CreateView, DetailView, UpdateView)
from django.http import HttpResponse, HttpResponseRedirect, request
from .models import Blog, Comment
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
#This ensures that user is logged in in order to create new database entry
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.detail import SingleObjectMixin
from django.utils import timezone, dateformat
from datetime import datetime
from .forms import CommentForm, BlogForm

# Create your views here.

class AboutView(TemplateView):
    template_name = 'my_app/about.html'

class PublishedBlogListView(ListView):
    model = Blog
    template_name = 'my_app/index.html'

    # def get_context_data(self, **kwargs):
    #     self.object = self.get_object()
    #     approved_count = self.object.comments
    #     return context

    def get_queryset(self):
        return Blog.objects.filter(state__exact=True)

class DraftBlogListView(LoginRequiredMixin, ListView):
    # This should be done whenever LoginRequiredMixin is inherited. login_url is url to display if user is not 
    # logged in, redirect_field is url to display after they login
    # NB: must have LoginRequiredMixin before Listview
    login_url = '/login/'
    #This does not work
    # redirect_field_name = 'my_app/drafts.html'
    
    model = Blog
    template_name = 'my_app/drafts.html'

    # This function overides the original. It has been modified to filter out all objects with state equal to False before ListView displays all.
    # https://docs.djangoproject.com/en/3.2/ref/class-based-views/
    # https://docs.djangoproject.com/en/3.2/ref/class-based-views/generic-display/#listview
    # https://docs.djangoproject.com/en/3.2/ref/models/querysets/#field-lookups  search field lookups
    # https://docs.djangoproject.com/en/3.2/topics/db/queries/#field-lookups

    def get_queryset(self):
        return Blog.objects.filter(state__exact=False)

    #Dont need to pass user object in with context dictionary. user object is already available in template as 'user'
    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     user = self.request.user
    #     #Can pass objects into templates!!!
    #     context['current_user'] = user
    #     return context


class BlogCreateView(LoginRequiredMixin ,CreateView):
    login_url = '/login/'
    # redirect_field_name = 'my_app/new_post.html'

    #I believe the default success_url is the blog details page 
    # fields = ['title', 'content']
    # https://docs.djangoproject.com/en/3.2/ref/class-based-views/mixins-editing/#django.views.generic.edit.FormMixin
    form_class = BlogForm
    model = Blog
    template_name = 'my_app/new_post.html'
    # success_url = "my_app/"

    #This is function sets the field/form parameters not passed to the template
    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.state = False
        # print(self.request.user)
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['create_blog'] = True
        return context

class BlogDetailView(DetailView):
    model = Blog
    context_object_name = 'blog'
    template_name = 'my_app/detail.html'

    # This is for injecting data
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = CommentForm()
        return context

    def post(self, *args, **kwargs):
        # print(self.request.POST)
        form = CommentForm(self.request.POST)
        print(form)
        if form.is_valid():
            # comment_author = form.cleaned_data["author"]
            # comment_text = form.cleaned_data["content"]
            comment = form.save(commit=False)
            comment.blog = self.get_object()
            comment.create_date = timezone.now()
            comment.status = False
            print("create date:", comment.create_date)
            # blog = self.get_object()
            comment.save()

            # comment_object, created = Comment.objects.get_or_create(author=comment_author, content=comment_text, status=False, blog=blog, create_date=create_date)
            # if created:
            #     print("comment created")
            # else:
            #     print("Comment already exists")
            # comment_object.save()
        return HttpResponseRedirect(reverse('my_app:detail', args=(comment.blog.pk,)))

    #I believe this function is called when http POST request occurs, it then gets the object this view is operating on and updates it 
    #https://docs.djangoproject.com/en/3.2/ref/class-based-views/base/#view
    #https://stackoverflow.com/questions/41203730/updating-a-single-object-field-in-django-view
    #https://docs.djangoproject.com/en/3.2/ref/class-based-views/mixins-single-object/#django.views.generic.detail.SingleObjectMixin

    # def post(self, *args, **kwargs):
    #     print("post method called")
    #     if self.request.POST.get("submit_publish"):
    #         print("Publish button pressed")
    #         self.object = self.get_object()
    #         self.object.state = True
    #         print(self.object.publish_date)
    #         # self.object.publish_date = dateformat.format(timezone.now(), "M. d, Y, h:i a")
    #         self.object.publish_date = timezone.now()
    #         print(self.object.publish_date)
    #         self.object.save(update_fields=('state', 'publish_date',))
    #         return HttpResponseRedirect(reverse('my_app:index'))

    #     elif self.request.POST.get("submit_comment"):
    #         #Create and save new comment object to database:
    #         print("comment button pressed")

    #         #Create a form instance from form data
    #         blog = self.get_object()
    #         comment_author = self.request.POST.get("author")
    #         comment_text = self.request.POST.get("comment_text")

    #         comment_object, created = Comment.objects.get_or_create(author=comment_author, content=comment_text, status=False, blog=blog)
    #         if created:
    #             print("comment created")
    #         comment_object.save()
    #         return HttpResponseRedirect(reverse('my_app:detail', args=(blog.pk,)))
        
    #     else:
    #         print('else executed')
    #         #https://docs.djangoproject.com/en/3.2/ref/models/querysets/#update
    #         self.object = self.get_object()
    #         print(self.object)
    #         print(self.request.POST)

    #         for val in self.request.POST:
    #             if val[0] == '$':
    #                 print("doller sign found")
    #                 comment_pk = val[2:]
    #                 print("comment_pk =", comment_pk)
    #                 comment_cmd = val[1]

    #         comment_queryset = self.object.comments.filter(pk=comment_pk)
    #         print(self.object.comments.filter(pk=comment_pk))

    #         if comment_cmd == 'a':
    #             print("command is approve")
    #             #change state of comment
    #             comment_queryset.update(status=True)

    #         elif comment_cmd =='r':
    #             print("command is reject")
    #             comment_queryset.delete()
            
    #         return HttpResponseRedirect(reverse('my_app:detail', args=(self.object.pk,)))
                    

class BlogUpdateView(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    # redirect_field_name = 'my_app/new_post.html'

    form_class = BlogForm
    model = Blog
    template_name = 'my_app/new_post.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['create_blog'] = False
        return context

class BlogDeleteView(LoginRequiredMixin, DeleteView):
    login_url = '/login/'

    model = Blog
    # template_name = 'my_app/blog_confirm_delete.html'
    #Reverse_lazy will ensure that blog object is deleted before url redirect occurs
    success_url = reverse_lazy('my_app:index')

# class CommentCreateView(CreateView):
#     model = comment
#     fields = ['content']
#     template_name = 'my_app/detail.html'
    

# def user_login(request):
    
#     #If user has sent data to server
#     if request.method == 'POST':
#         print("user has posted")
#         #Get info from form
#         user_name = request.POST["user_name"]
#         password = request.POST["password"]

#         #Authenticate user
#         user = authenticate(username=user_name, password=password)

#         if user != None:
#             print("Logging in user")
#             if user.is_active:
#                 login(request, user)
#                 return HttpResponseRedirect(reverse('my_app:index'))
#             else:
#                 return HttpResponse("User not active")
#         else:
#             #Should keep on login page and use template tagging to say credentials not valid
#             print("Error in credentials")
#             return HttpResponse("Error in credentials")

#     # else:
#         # user_form =UserForm()

#     return render(request, 'my_app/login.html')

# @login_required
# def user_logout(request):
#     logout(request)
#     return HttpResponseRedirect(reverse('my_app:index'))

# Blog handlers
def blog_publish(request, pk):
    blog = get_object_or_404(Blog, pk=pk)
    blog.publish()
    return HttpResponseRedirect(reverse('my_app:detail', args=(blog.pk,)))

# Comment-handling views

# Grab form data and create new comment object. Can also be done in post method of class

tech_blog/my_app/templates/my_app/about.html
{% extends 'my_app/my_app_base.html' %}
{% block body_block %}
<div class="row justify-content-center">
    <div class="col-8">
        <br>
        <h1>Info About The Development of this Website</h1>
        <p style="text-align:center;">This website is the first 
            full stack web development project that I have worked on. The frontend was developed using html, css, bootstrap and javascript. The backend was 
            developed in python using the Django web development framework.</p>
    </div>
</div>
{% endblock body_block %}

tech_blog/my_app/templates/my_app/blog_confirm_delete.html
{% extends 'my_app/my_app_base.html' %}

{% block body_block %}
<br>
<br>
<br>
<form class="delete_form" method="post">
    {% csrf_token %}
    <h4>Are you sure you want to delete "{{ blog.title }}"?</h4>
    <br>
    <input class="btn btn-danger" type="submit" value="Confirm">
</form>
{% endblock body_block %}

tech_blog/my_app/templates/my_app/detail.html
{% extends 'my_app/my_app_base.html' %}

{% block body_block %}
<div class="row justify-content-center">
    <div class="col-10">
        <h1> {{blog.title}} </h1>
        {% if blog.state == True %}
        {% comment %} https://docs.djangoproject.com/en/4.0/ref/templates/builtins/#date {% endcomment %}
        <p class="publish_date">{{blog.publish_date|date:"M, d, Y, "}}{{blog.publish_date|time:"h:i a"}}</p>
        {% endif %}
        <p style="text-align: center;"> Author: {{blog.user}} </p>
        {% comment %} The autoescape ensures that templatetag content is rendered as html {% endcomment %}
        {% comment %} Can also use {{blog.content|safe|linebreaksbr}} {% endcomment %}
        {% autoescape off %}
            {{blog.content}}
        {% endautoescape %} 
        {% comment %} <p> State: {{blog.state}} </p> {% endcomment %}
        <p> current_user: {{user}} </p>

        {% if user.is_authenticated %}
            {% if blog.user == user %}
                <a class="btn btn-primary" href="{% url 'my_app:update' pk=blog.pk%}"><i class="bi bi-pencil"></i></a>
                <a class="btn btn-primary" href="{% url 'my_app:delete' pk=blog.pk %}"><i class="bi bi-trash"></i></a>
                <br>
                <br>
                {% if not blog.state %}
                    {% comment %} <form method="post">
                        {% csrf_token %}
                        <input type="submit" name="submit_publish" value="Publish">
                    </form> 
                    {% csrf_token %}{% endcomment %}
                    <div style="text-align:center;">
                    <a class="btn btn-primary" href="{% url 'my_app:delete' pk=blog.pk %}" href="{% url 'my_app:blog_publish' pk=blog.pk%}">Publish</a>
                    </div>
                    {% endif %}
            {% endif %}
        {% endif %}
        <br>
        <br>
        {% if blog.state == True %}

            <div class="new_comment">
                <h4 class="luxury_font">Add Comment:</h4>
                {% comment %} <form method="post" action="/comment/create"> {% endcomment %}
                <form method="post">
                    {% csrf_token %}
                    {{comment_form.as_p}}
                    <input type="submit" class="btn btn-primary" value="Submit">
                    {% comment %} <p>
                    <label for="author">Author</label>
                    <input type="text" name="author" id="author">
                    </p>
                    <p>
                    <label for="comment_text">Comment</label>
                    <textarea name="comment_text" id="comment_text" cols="30" rows="10"></textarea>
                    </p>
                    <p>
                    <input type="submit" name="submit_comment" value="Comment">
                    </p> {% endcomment %}
                </form>
            </div>

            <br>
            <div class="approved_comments">
                <h4 class="luxury_font">Comments</h4>
                    {% for comment in blog.comments.all %}
                        {% if user.is_authenticated %}
                            {% if blog.user == user %}
                                {% if  comment.status == False%}
                                    {% autoescape off %}
                                        {{comment.content}}
                                    {% endautoescape %} 
                                    <div class="tight_spacing">
                                        <p>Author: {{comment.author}}</p>
                                        <p>Created: {{comment.create_date|date:"M, d, Y, "}}{{comment.create_date|time:"h:i a"}}</p>
                                        {% comment %} <p>State: {{comment.status}}</p> {% endcomment %}
                                        {% comment %} Put in buttons here {% endcomment %}
                                        <a class="btn btn-primary" href="{% url 'my_app:comment_approve' pk=comment.pk%}"><i class="bi bi-check"></i></a>
                                        <a class="btn btn-primary" href="{% url 'my_app:comment_reject' pk=comment.pk%}"><i class="bi bi-x"></i></a>
                                    </div>
                                    <br>
                                        
                                    <!--
                                    <form method="post">
                                        {% csrf_token %}
                                        <input type="submit" name="$a{{comment.pk}}" value="Approve">
                                        <input type="submit" name="$r{{comment.pk}}" value="Reject">
                                    </form>
                                    -->
                                {% endif %}
                            {% endif %}
                        {% endif %}
                    {% endfor %}

                    {% for comment in blog.comments.all %}
                            {% if  comment.status == True%}
                                <div class="tight_spacing">
                                    {% autoescape off %}
                                        {{comment.content}}
                                    {% endautoescape %} 
                                    <p>Author: {{comment.author}}</p>
                                    <p>Created: {{comment.create_date|date:"M, d, Y, "}}{{comment.create_date|time:"h:i a"}}</p>
                                    {% comment %} <p>State: {{comment.status}}</p> {% endcomment %}
                                </div>
                                <br>
                            {% endif %}
                    {% endfor %}
            </div>
        {% endif %}

    </div>
</div>
    
    <script>
        var comment = document.querySelector("#id_content")
        var editor = new MediumEditor(comment);
    </script>

{% endblock body_block %}

tech_blog/my_app/templates/my_app/drafts.html
{% extends 'my_app/my_app_base.html' %}

{% block body_block %}
<h1>Unpublished blogs:</h1>

{% for blog in blog_list %}

    {% if blog.user == user %}
        <div class="tight_spacing">
            {% comment %} {% if blog.state == False %} {% endcomment %}
            {% comment %} Line redudant as get_queryset() call overidden in views to include a filter to filter out ojects with false state{% endcomment %}
            {% comment %} Link should take you to update page {% endcomment %}
            <p><a href="{% url 'my_app:detail' pk=blog.pk %}">{{blog.title}}</a></p> 
            <p>Author: {{blog.user}}</p>
            {% comment %} <p>State: {{blog.state}}</p> {% endcomment %}
        </div>
    {% endif %}
{% endfor %}

{% endblock body_block %}

{% comment %} (blog.user == current_user) and {% endcomment %}

tech_blog/my_app/templates/my_app/index.html
{% extends 'my_app/my_app_base.html' %}
{% comment %} NB: Must load custom filter from html file you use them, wont work if they are in the base file!!!! {% endcomment %}
{% load comment_count %}

{% block body_block %}
<div class="row justify-content-center luxury_font">
    <div class="col-10">
        <h1>Published blogs</h1>

        {% for blog in blog_list %}
        <div class="tight_spacing">
            {% comment %} {% if blog.state == False %} {% endcomment %}
            {% comment %} Line redudant as get_queryset() call overidden in views to include a filter to filter out ojects with false state {% endcomment %}
            <p><a href="{% url 'my_app:detail' pk=blog.pk %}">{{blog.title}}</a></p> 
            <p>Author: {{blog.user}}</p>
            {% comment %} <p>State: {{blog.state}}</p> {% endcomment %}
            {% comment %} Only show approved comments {% endcomment %}
            <p>Comments: {{blog.comments.all|comment_count}}</a></p>
            {% comment %} <p><a href="{% url 'my_app:comment_list' %}">Comments: {{blog.comments.all.count}}</a></p> {% endcomment %}
            {% comment %} {% for comment in blog.comments.all %}
                <p>{{comment.content}}</p>
            {% endfor %} {% endcomment %}
        </div>
            <br>
        {% endfor %}
    </div>
</div>

{% endblock body_block %}

tech_blog/my_app/templates/my_app/login.html
{% extends 'my_app/my_app_base.html' %}

{% block body_block %}

    {% comment %} {% if form.errors %}
        <p>Your username or password were incorrect, please try agan.</p>
    {% endif %}

    <h1>Enter your login details</h1>
        {# NB: Must have method and not action here #}
        <form method="POST"> 
        {% csrf_token %}
        <p>
            <label for="user_name">User Name:</label>
            <input type="text" name="user_name" id="user_name">
        </p>

        <p>
            <label for="password">Password:</label>
            <input type="password" name="password" id="password">
        </p>

        <input type="submit" value="Login">
        </form> {% endcomment %}

        {% comment %} Straight from django: https://docs.djangoproject.com/en/4.0/topics/auth/default/#module-django.contrib.auth.views {% endcomment %}
       <div class="row justify-content-center">
           <div class="col-4 login_form">
                {% if form.errors %}
                <p>Your username and password didn't match. Please try again.</p>
                {% endif %}
                
                {% if next %}
                    {% if user.is_authenticated %}
                    <p>Your account doesn't have access to this page. To proceed,
                    please login with an account that has access.</p>
                    {% else %}
                    <p>Please login to see this page.</p>
                    {% endif %}
                {% endif %}
                
                <form method="post" action="{% url 'login' %}">
                {% csrf_token %}
                <table>
                <tr>
                    <td>{{ form.username.label_tag }}</td>
                    <td>{{ form.username }}</td>
                </tr>
                <tr>
                    <td>{{ form.password.label_tag }}</td>
                    <td>{{ form.password }}</td>
                </tr>
                </table>
                
                <input type="submit" class="btn btn-primary" value="login">
                <input type="hidden" name="next" value="{{ next }}">
                </form>
                
                {# Assumes you set up the password_reset view in your URLconf #}
                {% comment %} <p><a href="{% url 'password_reset' %}">Lost password?</a></p> {% endcomment %}
            </div>
        </div>

{% endblock body_block %}

tech_blog/my_app/templates/my_app/my_app_base.html
<!DOCTYPE html>
{% load static %}
{% load comment_count %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'css/my_app.css' %}">

    {% comment %} medium-editor {% endcomment %}
    <link rel="stylesheet" href="{% static 'css/medium-editor.css' %}">
    <link rel="stylesheet" href="{% static 'css/default.css' %}">
    <script src="{% static 'js/medium-editor.js' %}"></script>

    {% comment %} Font import {% endcomment %}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster&family=Luxurious+Roman&family=Montserrat&display=swap" rel="stylesheet"> 
    {% comment %} Bootstrap icons {% endcomment %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    
    <title>Tech Blog</title>
</head>
<body class="loader">
    <nav class="navbar navbar-expand-lg navbar-light bg-light luxury_font">
        <div class="container-lg">
          <a class="navbar-brand big_brand" href="{% url 'my_app:index' %}">Tech Blog</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'my_app:about' %}">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://github.com/20436386">Github</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">LinkedIn</a>
              </li>
            </ul>
            <ul class="navbar-nav ms-auto">
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'my_app:new_post' %}">New Post</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'my_app:drafts' %}">Drafts</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Logout</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Welcome: {{user}}</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}"><i class="bi bi-person-circle"></i></a>
              </li>
              {% endif %}

            </ul>
          </div>
        </div>
      </nav>

      <div class="container-lg">
        <div class="row justify-content-center luxury_font">
          <div class="col-10">
            {% block body_block %}
            
            {% endblock body_block %}
          </div>
        </div>
      </div>
</body>
</html>

tech_blog/my_app/templates/my_app/new_post.html
{% extends 'my_app/my_app_base.html' %}

{% block body_block %}

    {% if create_blog %}
        <h1>Create New Blog:</h1>
    {% else %}
        <h1>Update Blog:</h1>
    {% endif %}
    <br>

    <div style="text-align: center;">
            {% csrf_token %}
            {{form.as_p}}    
            <input type="submit" class="btn btn-primary" value="Save">
        </form>
    </div>

    <script>
        var textArea = document.querySelector("#id_content")
        var editor = new MediumEditor(textArea);

    </script>

{% endblock body_block %}